<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Jinja Syntax</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\{\{.+(\|.+)\}\}</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{\{.+\}\}</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{%.+%\}</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{#</string>
			<key>end</key>
			<string>#\}</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jinja</string>
	<key>uuid</key>
	<string>8287aa29-b2d2-45e8-9352-c271a90ccf33</string>
</dict>
</plist>
